# NumPy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.3'

In [3]:
list1 = [1,2,3,4,5]

arr = np.array(list1)

arr

array([1, 2, 3, 4, 5])

In [4]:
arr.ndim

1

In [5]:
arr1 = np.array([[1,2,3], [4,5,6], [6,7,8]])

In [6]:
arr1.ndim

2

In [7]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
np.asarray([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.array([[[1,2,3], [4,5,6], [7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [10]:
np.asarray([[[1,2,3], [4,5,6], [7,8,9]]])


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
### Matrix is 2d array (subclass of ndarray)
mat = np.matrix([1,2,3,4])

In [12]:
mat

matrix([[1, 2, 3, 4]])

In [13]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [14]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [15]:
mat.shape

(1, 4)

In [16]:
mat.size

4

In [17]:
np.fromfunction(lambda x,y: x == y, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [19]:
np.fromiter(range(5), int)

array([0, 1, 2, 3, 4])

In [21]:
np.fromstring('23 45 60', sep=' ')

array([23., 45., 60.])

In [22]:
arr = np.array([1,2,3,4,5])
arr1 = arr.copy()

In [23]:
arr

array([1, 2, 3, 4, 5])

In [24]:
arr1

array([1, 2, 3, 4, 5])

In [29]:
np.fromstring('23,24,25,26', sep=',', dtype=int)

array([23, 24, 25, 26])

In [30]:
range(0.0, 10.1)

TypeError: 'float' object cannot be interpreted as an integer

In [31]:
np.arange(start=0.0, step=0.1, stop=5)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [35]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [38]:
np.logspace(1,5, 20, base=2)

array([ 2.        ,  2.31422047,  2.6778082 ,  3.09851928,  3.58532838,
        4.14862018,  4.80041088,  5.55460457,  6.42728981,  7.43708284,
        8.60552469,  9.95754072, 11.5219723 , 13.3321921 , 15.42681597,
       17.85052668, 20.65502717, 23.90014339, 27.65510059, 32.        ])

In [41]:
np.logspace(2,4, 2, base=2)

array([ 4., 16.])

In [44]:
np.zeros(2)

array([0., 0.])

In [48]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [56]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [58]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
np.ones((2,3)) + 3

array([[4., 4., 4.],
       [4., 4., 4.]])

#### NumPy - 

#### Array

#### Array vs List

#### Why are arrays faster than list?

Ans. Since it is homogenous and memory allocation is contigous so it retrieval is fast. In case of list actual data is stored not contigously but the memory address of data is stored in contigous memory.

#### 

Ans.