# NumPy

In [2]:
import numpy as np

In [1]:
np.__version__

2

In [3]:
list1 = [1,2,3,4,5]

arr = np.array(list1)

arr

array([1, 2, 3, 4, 5])

In [4]:
arr.ndim

1

In [5]:
arr1 = np.array([[1,2,3], [4,5,6], [6,7,8]])

In [6]:
arr1.ndim

2

In [7]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
np.asarray([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.array([[[1,2,3], [4,5,6], [7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [10]:
np.asarray([[[1,2,3], [4,5,6], [7,8,9]]])


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
### Matrix is 2d array (subclass of ndarray)
mat = np.matrix([1,2,3,4])

In [12]:
mat

matrix([[1, 2, 3, 4]])

In [13]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [14]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [15]:
mat.shape

(1, 4)

In [16]:
mat.size

4

In [17]:
np.fromfunction(lambda x,y: x == y, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [19]:
np.fromiter(range(5), int)

array([0, 1, 2, 3, 4])

In [21]:
np.fromstring('23 45 60', sep=' ')

array([23., 45., 60.])

In [22]:
arr = np.array([1,2,3,4,5])
arr1 = arr.copy()

In [23]:
arr

array([1, 2, 3, 4, 5])

In [24]:
arr1

array([1, 2, 3, 4, 5])

In [29]:
np.fromstring('23,24,25,26', sep=',', dtype=int)

array([23, 24, 25, 26])

In [30]:
range(0.0, 10.1)

TypeError: 'float' object cannot be interpreted as an integer

In [31]:
np.arange(start=0.0, step=0.1, stop=5)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [35]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [38]:
np.logspace(1,5, 20, base=2)

array([ 2.        ,  2.31422047,  2.6778082 ,  3.09851928,  3.58532838,
        4.14862018,  4.80041088,  5.55460457,  6.42728981,  7.43708284,
        8.60552469,  9.95754072, 11.5219723 , 13.3321921 , 15.42681597,
       17.85052668, 20.65502717, 23.90014339, 27.65510059, 32.        ])

In [41]:
np.logspace(2,4, 2, base=2)

array([ 4., 16.])

In [44]:
np.zeros(2)

array([0., 0.])

In [48]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [56]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [58]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
np.ones((2,3)) + 3

array([[4., 4., 4.],
       [4., 4., 4.]])

In [4]:
arr = np.random.randint(1, 100, (4, 5))

In [5]:
arr

array([[99, 98, 80,  7, 21],
       [63, 91, 72, 86, 25],
       [45, 58, 91, 14, 50],
       [ 7, 67, 29, 67, 44]])

In [6]:
arr.reshape(-1, 4)

array([[99, 98, 80,  7],
       [21, 63, 91, 72],
       [86, 25, 45, 58],
       [91, 14, 50,  7],
       [67, 29, 67, 44]])

In [8]:
arr.reshape((2,2,-1))

array([[[99, 98, 80,  7, 21],
        [63, 91, 72, 86, 25]],

       [[45, 58, 91, 14, 50],
        [ 7, 67, 29, 67, 44]]])

In [9]:
arr1 = np.random.randint(1, 100, (5,4))
arr1

array([[53, 76, 41, 14],
       [46, 73, 21, 29],
       [43, 28, 59, 85],
       [80, 77, 48, 54],
       [15, 52, 72, 29]])

In [10]:
arr1 > 45

array([[ True,  True, False, False],
       [ True,  True, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True, False]])

In [11]:
arr1[arr1 > 45]

array([53, 76, 46, 73, 59, 85, 80, 77, 48, 54, 52, 72])

In [12]:
arr1

array([[53, 76, 41, 14],
       [46, 73, 21, 29],
       [43, 28, 59, 85],
       [80, 77, 48, 54],
       [15, 52, 72, 29]])

In [13]:
arr1 * 5

array([[265, 380, 205,  70],
       [230, 365, 105, 145],
       [215, 140, 295, 425],
       [400, 385, 240, 270],
       [ 75, 260, 360, 145]])

In [22]:
arr1[2:3]

array([[43, 28, 59, 85]])

In [23]:
arr[0]

array([99, 98, 80,  7, 21])

In [24]:
arr[0][1:]

array([98, 80,  7, 21])

In [35]:
arr[0]

array([99, 98, 80,  7, 21])

In [36]:
arr[0, [1,3]]

array([98,  7])

In [34]:
arr[0:3, 1:4]

array([[98, 80,  7],
       [91, 72, 86],
       [58, 91, 14]])

In [37]:
arr1

array([[53, 76, 41, 14],
       [46, 73, 21, 29],
       [43, 28, 59, 85],
       [80, 77, 48, 54],
       [15, 52, 72, 29]])

In [38]:
arr1.argsort()

array([[3, 2, 0, 1],
       [2, 3, 0, 1],
       [1, 0, 2, 3],
       [2, 3, 1, 0],
       [0, 3, 1, 2]], dtype=int64)

In [39]:
arr1.argmin()

3

In [40]:
arr1.argmax()

11

In [41]:
arr1.argmax(axis=1)

array([1, 1, 3, 0, 2], dtype=int64)

In [42]:
import random

random.choice([1,2,3,4,5])

4

In [46]:
arr1

array([[53, 76, 41, 14],
       [46, 73, 21, 29],
       [43, 28, 59, 85],
       [80, 77, 48, 54],
       [15, 52, 72, 29]])

In [47]:
arr2 = np.random.randint(0, 100, (5,4))

In [48]:
arr2

array([[21, 28, 26, 35],
       [14, 15,  3, 49],
       [69, 43, 36, 87],
       [97, 31, 43, 94],
       [46, 75, 75, 89]])

In [49]:
arr1 + arr2

array([[ 74, 104,  67,  49],
       [ 60,  88,  24,  78],
       [112,  71,  95, 172],
       [177, 108,  91, 148],
       [ 61, 127, 147, 118]])

In [50]:
arr1 * arr2

array([[1113, 2128, 1066,  490],
       [ 644, 1095,   63, 1421],
       [2967, 1204, 2124, 7395],
       [7760, 2387, 2064, 5076],
       [ 690, 3900, 5400, 2581]])

In [51]:
arr1.dot(arr2)

ValueError: shapes (5,4) and (5,4) not aligned: 4 (dim 1) != 5 (dim 0)

In [52]:
arr2 = np.random.randint(0,100, (4,5))

In [53]:
arr1.dot(arr2)

array([[ 9810, 13843,  9235,  6927,  7711],
       [10072, 12744,  9417,  6098,  7859],
       [12033, 14906, 10638,  8605, 10968],
       [14411, 19407, 12871,  9123, 11558],
       [ 8359, 11224,  8371,  8200,  7992]])

In [54]:
arr1 @ arr2

array([[ 9810, 13843,  9235,  6927,  7711],
       [10072, 12744,  9417,  6098,  7859],
       [12033, 14906, 10638,  8605, 10968],
       [14411, 19407, 12871,  9123, 11558],
       [ 8359, 11224,  8371,  8200,  7992]])

In [55]:
np.empty((4,5))

array([[6.23042070e-307, 1.89146896e-307, 1.37962320e-306,
        1.78019354e-306, 1.86915711e-306],
       [1.78017181e-306, 2.22525550e-307, 4.22796967e-307,
        1.33511290e-306, 1.37959129e-306],
       [9.34609111e-307, 2.22520559e-306, 9.34609111e-307,
        9.34609790e-307, 1.24610723e-306],
       [8.90104917e-307, 1.37961913e-306, 1.11259601e-306,
        1.24608686e-306, 6.23059726e-307]])

In [56]:
arr_empty = np.empty((2,3))

In [57]:
arr_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
arr_1 = np.zeros((5,4))
arr_1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
arr_2 = [1,2,3,4]
arr_1 + arr_2

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [73]:
arr_3 = np.array([[1,2,3,4,5]])
arr_1 + arr_3

ValueError: operands could not be broadcast together with shapes (5,4) (1,5) 

In [74]:
arr_3.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [75]:
arr_1 + arr_3.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [76]:
arr1 = np.array([1,2,3,4,5])

np.expand_dims(arr1, axis = 0)

array([[1, 2, 3, 4, 5]])

In [77]:
np.expand_dims(arr1, axis = 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])