## NumPy Assignment

### 1. What is a Python library? Why do we use Python libraries?

*Ans.* 
A Python library is a reusable collection of code that offers pre-written functionalities to perform various tasks. We use Python libraries for code efficiency, reusability, and access to specialized tools across domains like data science, web development, and more. 

Here are key reasons why we use Python libraries:

##### 1. Code Reusability
##### 2. Community Collaboration
##### 3. Standardization
##### 4. Efficiency
##### 5. Open Source

### 2. What is the difference between Numpy array and List?

| Category  | List | NumPy Array |
|-----------|------|-------------|
| Data Type | Lists can contain elements of different data types | NumPy arrays are homogeneous, meaning all elements must have the same data type. |
| Memory Efficiency | Less Efficient | More memory efficient as they store elements in contiguous memory locations |
| Performance | Lists are generally slower for numerical operations and mathematical computations. | NumPy arrays are optimized for numerical operations, making them faster and more efficient. |
| Functionality | Lists provide general-purpose functionalities and are more flexible for basic tasks. | NumPy arrays offer a wide range of mathematical operations and functions specifically designed for numerical computations. |
| Size Manipulation | Lists can easily change size (grow or shrink) dynamically. | NumPy arrays have a fixed size upon creation, and resizing requires creating a new array. |

### 3. Find the shape, size and dimension of the following array?
```
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

*Ans.*
#### Size is 12
#### Shape is (3,4)
#### Dimension is 2

below is code to find it.

In [44]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])

print(arr)
print()
print(f'Size is = {arr.size}')
print(f'Shape is = {arr.shape}')
print(f'Dimension is = {arr.ndim}')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Size is = 12
Shape is = (3, 4)
Dimension is = 2


### 4. Write python code to access the first row of the following array?
```
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [6]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])

first_row = arr[0]

print(first_row)

[1 2 3 4]


### 5. How do you access the element at the third row and fourth column from the given numpy array?
```
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [7]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])

element_at_3row_4col = arr[2][3]

print(f'Element at 3rd row and 4th column is {element_at_3row_4col}')

Element at 3rd row and 4th column is 12


### 6. Write code to extract all odd-indexed elements from the given numpy array?
```
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [43]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])

## For odd-indexed column elements
odd_col_indexed_element = arr[:, 1::2]

print(f'Odd column indexed elements \n{odd_col_indexed_element}')

## For odd-indexed row elements
odd_row_indexed_element = arr[1::2, :]

print(f'\nOdd rows indexed elements \n{odd_row_indexed_element}')

## For odd-indexed row elements
odd_row_col_indexed_element = arr[1::2, 1::2]

print(f'\nOdd row and column indexed elements \n{odd_row_col_indexed_element}')


Odd column indexed elements 
[[ 2  4]
 [ 6  8]
 [10 12]]

Odd rows indexed elements 
[[5 6 7 8]]

Odd row and column indexed elements 
[[6 8]]


### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [13]:
import numpy as np

result = np.random.rand(3,3)

print(result)

[[0.2717977  0.1142571  0.60912126]
 [0.99987433 0.56819399 0.01890041]
 [0.90015984 0.04132974 0.47269387]]


### 8. Describe the difference between np.random.rand and np.random.randn?

| np.random.rand | np.random.randn |
| -------------- | --------------- |
| Generates random values from a uniform distribution over the interval `[0, 1)`. | Generates random values from a standard normal distribution (mean = 0, standard deviation = 1). |


Examples as below:

In [16]:
import numpy as np

# Example: Generate a 2x2 matrix with random values between 0 and 1
random_matrix = np.random.rand(2, 2)

print(random_matrix)
print()
# Example: Generate a 2x2 matrix with random values from a standard normal distribution
random_matrix_normal = np.random.randn(2, 2)

print(random_matrix_normal)

[[0.44665931 0.50575917]
 [0.17631013 0.6702959 ]]

[[ 0.80670266 -1.13988208]
 [-0.6410971  -1.32311667]]


### 9. Write code to increase the dimension of the following array?
```
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [17]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])

result = np.expand_dims(arr, axis=0)

print(result)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


### 10. How to transpose the following array in NumPy?
```
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [18]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])

tranpose_arr = arr.T

print(tranpose_arr)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 11. Consider the following matrix:
* Matrix A:  `[[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]`

* Matrix B:  `[[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]`

### Perform the following operation using Python1
1. Index wise multiplication
2. Matix multiplication
3. Add both the matrics
4. Subtact matix B from A
5. Divide Matrix B by A

In [22]:
import numpy as np

arr_A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

arr_B = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print('Array A is ')
print(arr_A)
print()
print('Array B is ')
print(arr_B)

Array A is 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array B is 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##### 1. Index wise multiplication

In [23]:
mul_result = arr_A * arr_B

print('Result of Index wise multiplication:')
print(mul_result)

Result of Index wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


##### 2. Matix multiplication

*Ans.* Matrix multiplication is not possible between 3x4 and 3x4 arrays as number columns in one and number or rows in second does not match.

In [26]:
mat_mult_result = arr_A @ arr_B

print('Result of Matix multiplication:')
print(mat_mult_result)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

We can multiply using transpose of arr_B, 3*4 ad 4*3 arrays.

In [25]:
mat_mult_result_1 = arr_A @ arr_B.T

print('Result of Matix multiplication:')
print(mat_mult_result_1)

Result of Matix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


##### 3. Add both the matrics

In [27]:
addition_result = arr_A + arr_B

print('Result of Addition:')
print(addition_result)

Result of Addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


##### 4. Subtact matix B from A

In [28]:
diff_result = arr_A - arr_B

print('Result of A - B:')
print(diff_result)

Result of A - B:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


##### 5. Divide Matrix B by A

In [29]:
div_result = arr_A / arr_B

print('Result of A / B:')
print(div_result)

Result of A / B:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 12. Which function in Numpy can be used to swap the byte order of an array?

*Ans.* 
In NumPy, the function used to swap the byte order of an array is numpy.ndarray.byteswap. This function swaps the byte order of the elements of an array in-place.

Below is an example:

In [30]:
import numpy as np

original_array = np.array([1, 2, 3, 4], dtype=np.int32)

swapped_array = original_array.byteswap()

print("Original Array:", original_array)
print("Swapped Array:", swapped_array)


Original Array: [1 2 3 4]
Swapped Array: [16777216 33554432 50331648 67108864]


### 13. What is the significance of the np.linalg.inv function?

*Ans.* The np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a square matrix.

If A is a square matrix and B = np.linalg.inv(A), then A.dot(B) (or np.dot(A, B)) should be close to the identity matrix, and vice versa.

Example as below:

In [35]:
import numpy as np

# Create a 2x2 matrix
A = np.array([[4, 7], [2, 6]])

# Calculate the inverse
A_inv = np.linalg.inv(A)

# Check the product A * A_inv (should be close to the identity matrix)
identity_check = np.allclose(np.dot(A, A_inv), np.eye(2))

print("Original Matrix:")
print(A)

print("\nInverse Matrix:")
print(A_inv)

print("\nDot of Original and Inverse:")
print(np.dot(A, A_inv))

print("\nCheck A * A_inv is close to the identity matrix:", identity_check)


Original Matrix:
[[4 7]
 [2 6]]

Inverse Matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]

Dot of Original and Inverse:
[[ 1.00000000e+00 -1.11022302e-16]
 [-1.11022302e-16  1.00000000e+00]]

Check A * A_inv is close to the identity matrix: True


### 14. What does the np.reshape function do, and how is it used?

*Ans.* The np.reshape function in NumPy is used to change the shape of an array without changing its data. It returns a new array with the same data but a different shape.

Below is example: 

In [36]:
import numpy as np

# Create a 1D array with 12 elements
original_array = np.arange(12)

# Reshape the array to a 3x4 matrix
reshaped_array = np.reshape(original_array, (3, 4))

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 15. What is broadcasting in Numpy?

*Ans.* Broadcasting in NumPy is a feature that facilitates arithmetic operations between arrays with different shapes and sizes. It automatically adjusts the dimensions of smaller arrays, making them compatible for element-wise operations with larger arrays. The key rules involve comparing dimensions element-wise, padding dimensions with ones, and determining the maximum size for each dimension in the result shape. This allows for concise and efficient code when performing operations on arrays with varying shapes.

In [37]:
import numpy as np

# Create a 2x3 matrix
A = np.array([[1, 2, 3], [4, 5, 6]])

# Add a 1D array to each row of the matrix
B = np.array([10, 20, 30])

# Broadcasting: B is "padded" become [[10, 20, 30], [10, 20, 30]]
result = A + B

print("Matrix A:")
print(A)

print("\nArray B:")
print(B)

print("\nResult of A + B:")
print(result)


Matrix A:
[[1 2 3]
 [4 5 6]]

Array B:
[10 20 30]

Result of A + B:
[[11 22 33]
 [14 25 36]]
